# Form implementation generated from reading ui file 'wind_test.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ADASDASDASD(object):
    def setupUi(self, ADASDASDASD):
        ADASDASDASD.setObjectName("ADASDASDASD")
        ADASDASDASD.resize(400, 355)
        self.lb_res = QtWidgets.QLabel(ADASDASDASD)
        self.lb_res.setGeometry(QtCore.QRect(120, 160, 131, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 23, 124))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 23, 124))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 23, 124))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 23, 124))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 23, 124))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 23, 124))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 23, 124))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 23, 124))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 23, 124))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.ButtonText, brush)
        self.lb_res.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setBold(True)
        font.setWeight(75)
        self.lb_res.setFont(font)
        self.lb_res.setAutoFillBackground(False)
        self.lb_res.setStyleSheet("color: rgb(255, 23, 124);")
        self.lb_res.setText("")
        self.lb_res.setObjectName("lb_res")
        self.label = QtWidgets.QLabel(ADASDASDASD)
        self.label.setGeometry(QtCore.QRect(20, 80, 68, 29))
        self.label.setObjectName("label")
        self.le_navn = QtWidgets.QTextEdit(ADASDASDASD)
        self.le_navn.setGeometry(QtCore.QRect(100, 80, 145, 31))
        self.le_navn.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CursorShape.IBeamCursor))
        self.le_navn.setObjectName("le_navn")
        self.pushButton = QtWidgets.QPushButton(ADASDASDASD)
        self.pushButton.setGeometry(QtCore.QRect(250, 80, 131, 31))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(ADASDASDASD)
        self.pushButton.clicked.connect(ADASDASDASD.velkommen) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ADASDASDASD)

    def retranslateUi(self, ADASDASDASD):
        _translate = QtCore.QCoreApplication.translate
        ADASDASDASD.setWindowTitle(_translate("ADASDASDASD", "Dialog"))
        self.label.setText(_translate("ADASDASDASD", "Hva heter du?"))
        self.le_navn.setHtml(_translate("ADASDASDASD", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.pushButton.setText(_translate("ADASDASDASD", "Si velkommen!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ADASDASDASD = QtWidgets.QDialog()
    ui = Ui_ADASDASDASD()
    ui.setupUi(ADASDASDASD)
    ADASDASDASD.show()
    sys.exit(app.exec())
